[project]
name = "delete"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "advertorch>=0.2.3",
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "omegaconf>=2.3.0",
    "scikit-learn>=1.7.2",
    "timm>=1.0.20",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
